name: mercure-totalsegmentator
channels:
  - conda-forge
dependencies:
  - python=3.9
  - dcm2niix
  - pydicom
  - pytorch
  - torchvision
  - jupyterlab
  - cudatoolkit=11.1
  - pip
  - pip :
    - scikit-learn 
    - TotalSegmentator
    - monai-deploy-app-sdk
    - typeguard~=2.12.1 # Work around MONAI requirements.txt bug that picks up the wrong typeguard version
    - highdicom
    - rt-utils

