name: mercure-totalsegmentator
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - dcm2niix  
  - numpy<2
  - pydicom
  - jupyterlab
  - pip
  - pip :
    - torch==2.3.0  -f  https://download.pytorch.org/whl/cu111/torch_stable.html
    - torchvision==0.18.0 -f https://download.pytorch.org/whl/cu111/torch_stable.html
    - SimpleITK
    - nibabel
    - p_tqdm
    - xvfbwrapper
    - dicom2nifti
    - pyarrow
    - nnunetv2==2.5.1
    - tqdm
    - scikit-learn
    - TotalSegmentator==2.4.0
    - monai-deploy-app-sdk==0.5.0
    - matplotlib==3.6.2
    - typeguard~=2.12.1 # Work around MONAI requirements.txt bug that picks up the wrong typeguard version
    - highdicom
    - rt-utils

